application: amcolash-art107
version: 1
runtime: python27
api_version: 1
threadsafe: yes

#default_expiration: "30d"

handlers:

- url: /(.*\.(html|gif|png|jpg|ico|js|css|pdf|txt))
  static_files: \1
  upload: (.*\.(html|gif|png|jpg|ico|js|css|pdf|txt))

- url: /
  static_files: index.html
  upload: index.html